// Ship class stats. Tuned so fighters are nimble glass cannons and
// battleships are slow walls. Expect to retune from playtest.
export const CLASSES = {
  fighter: {
    name: "Fighter",
    hp: 40,
    maxSpeed: 260,
    accel: 600,
    drag: 0.985,
    turnRate: 4.5,
    radius: 10,
    color: "#9cf",
    weapon: {
      damage: 6,
      cooldown: 0.12,    // seconds
      projectileSpeed: 720,
      range: 540,
      spread: 0.04,
      muzzles: 1,
      projectileRadius: 2,
      projectileColor: "#cff",
    },
    aiRange: 380,
    aiOrbit: 220,
  },
  frigate: {
    name: "Frigate",
    hp: 140,
    maxSpeed: 170,
    accel: 280,
    drag: 0.99,
    turnRate: 2.2,
    radius: 18,
    color: "#bdf",
    weapon: {
      damage: 10,
      cooldown: 0.22,
      projectileSpeed: 640,
      range: 700,
      spread: 0.03,
      muzzles: 2,
      muzzleSpread: 8,
      projectileRadius: 2.5,
      projectileColor: "#cef",
    },
    aiRange: 560,
    aiOrbit: 420,
  },
  cruiser: {
    name: "Cruiser",
    hp: 380,
    maxSpeed: 120,
    accel: 180,
    drag: 0.992,
    turnRate: 1.4,
    radius: 30,
    color: "#aaf",
    weapon: {
      damage: 22,
      cooldown: 0.32,
      projectileSpeed: 560,
      range: 880,
      spread: 0.02,
      muzzles: 2,
      muzzleSpread: 18,
      projectileRadius: 3.5,
      projectileColor: "#bdf",
    },
    aiRange: 760,
    aiOrbit: 620,
  },
  battleship: {
    name: "Battleship",
    hp: 900,
    maxSpeed: 75,
    accel: 100,
    drag: 0.994,
    turnRate: 0.7,
    radius: 52,
    color: "#88f",
    weapon: {
      damage: 36,
      cooldown: 0.28,
      projectileSpeed: 520,
      range: 1100,
      spread: 0.05,
      muzzles: 4,
      muzzleSpread: 30,
      projectileRadius: 4.5,
      projectileColor: "#acf",
    },
    aiRange: 980,
    aiOrbit: 820,
  },
};

// Side color palette: each ship tints its class color with side accent.
export const SIDES = {
  blue: { primary: "#5cf", accent: "#28a", name: "Allied" },
  red:  { primary: "#f76", accent: "#a33", name: "Hostile" },
};
