// Destructible ship subsystems.
//
// Capitals (battleship / carrier / cruiser) carry a full module roster:
// turret clusters, broadside batteries, missile bays, hangar, heavy-laser
// mount, plus engines. Smaller ships (fighter / bomber / frigate) carry
// only engine modules. Stations don't move, so no engine modules.
//
// Engines are special: each visible plume is its OWN targetable module
// (engine-0, engine-1, ...). Lose one engine on a 6-engine battleship
// and that plume goes dark and max speed drops to 5/6. Lose them all
// and the ship goes dead in the water. The static MODULES table below
// lists everything EXCEPT engines; engines are appended at spawn time
// by buildModules() based on the per-class plume count in ENGINES.
//
// Modules have their own HP and a position on the ship's local frame.
// Targeted damage that lands on a module's disc drains that module's HP
// independently of the central hull. When a module reaches 0 HP it
// becomes permanently `disabled` and drains its `hullPenalty` from the
// ship's central HP in one shot — so stripping modules accelerates the
// kill rather than replacing it.

import { ENGINES, ENGINE_X } from "./sprites.js";

// HP / hullPenalty for one engine module, per class.
const ENGINE_MODULE = {
  fighter:    { hp:  18, hullPenalty:  8 },
  bomber:     { hp:  32, hullPenalty: 15 },
  frigate:    { hp:  50, hullPenalty: 20 },
  cruiser:    { hp:  50, hullPenalty: 18 },
  battleship: { hp:  60, hullPenalty: 18 },
  carrier:    { hp:  70, hullPenalty: 28 },
};

// Disc radius of an engine module (normalized to ship.spec.radius).
// Bumped roughly 60% over the original layout — the previous battleship
// engine radius (0.075 → 11.7px disc on a 156px hull) was too small to
// reliably target during a strafing run. The new sizes are still
// tighter than other modules so adjacent plumes don't merge into one
// blob, but they're big enough to aim at.
const ENGINE_RADIUS = {
  fighter: 0.34, bomber: 0.32,
  frigate: 0.26, cruiser: 0.18,
  battleship: 0.13, carrier: 0.20,
};

// Offsets and radii are normalized to spec.radius (same convention as
// hull polygons): offset.x of 0.7 means 70% of the ship's radius along
// its forward axis. Static MODULES below lists non-engine modules only;
// engine-* entries are generated by buildModules() from ENGINES[klass].
// Radii bumped ~35% over the original layout so each module disc reads
// as a clear, deliberately targetable feature on the silhouette rather
// than a tiny pip. Offsets nudged where the larger discs would have
// collided with neighbours — see auditModuleLayout() below.
export const MODULES = {
  battleship: [
    { name: "laser",          offset: { x:  0.72, y:  0.00 }, radius: 0.30, hp: 220, hullPenalty: 100 },
    { name: "missile-fwd",    offset: { x:  0.15, y:  0.00 }, radius: 0.27, hp: 160, hullPenalty: 80  },
    { name: "missile-aft",    offset: { x: -0.45, y:  0.00 }, radius: 0.25, hp: 160, hullPenalty: 80  },
    { name: "broadside-port", offset: { x: -0.10, y: -0.70 }, radius: 0.32, hp: 200, hullPenalty: 100 },
    { name: "broadside-stbd", offset: { x: -0.10, y:  0.70 }, radius: 0.32, hp: 200, hullPenalty: 100 },
    { name: "pd-bow",         offset: { x:  0.50, y:  0.42 }, radius: 0.28, hp: 120, hullPenalty: 50  },
    { name: "pd-stern",       offset: { x: -0.58, y:  0.42 }, radius: 0.28, hp: 120, hullPenalty: 50  },
  ],
  carrier: [
    { name: "hangar",         offset: { x:  0.00, y:  0.00 }, radius: 0.38, hp: 300, hullPenalty: 150 },
    { name: "pd-port",        offset: { x:  0.10, y: -0.58 }, radius: 0.32, hp: 140, hullPenalty: 60  },
    { name: "pd-stbd",        offset: { x:  0.10, y:  0.58 }, radius: 0.32, hp: 140, hullPenalty: 60  },
  ],
  cruiser: [
    { name: "broadside-port", offset: { x: -0.10, y: -0.70 }, radius: 0.30, hp: 150, hullPenalty: 70 },
    { name: "broadside-stbd", offset: { x: -0.10, y:  0.70 }, radius: 0.30, hp: 150, hullPenalty: 70 },
    { name: "torpedo-bay",    offset: { x:  0.28, y:  0.00 }, radius: 0.27, hp: 140, hullPenalty: 70 },
    { name: "pd-cluster",     offset: { x: -0.55, y:  0.00 }, radius: 0.28, hp: 100, hullPenalty: 50 },
  ],
};

// Dev-only one-shot sanity check that no two non-engine module discs
// overlap by more than ~25% of their combined radii (centerDist <
// 0.75 * (rA+rB)). Logs a console.warn per offending pair so the
// MODULES table above can be nudged before shipping. Gated on Vite's
// import.meta.env.DEV so production builds don't carry the check.
let _layoutAuditDone = false;
export function auditModuleLayout() {
  if (_layoutAuditDone) return;
  _layoutAuditDone = true;
  if (!(typeof import.meta !== "undefined" && import.meta.env && import.meta.env.DEV)) return;
  for (const klass of Object.keys(MODULES)) {
    const mods = MODULES[klass];
    for (let i = 0; i < mods.length; i++) {
      for (let j = i + 1; j < mods.length; j++) {
        const a = mods[i], b = mods[j];
        const dx = a.offset.x - b.offset.x;
        const dy = a.offset.y - b.offset.y;
        const dist = Math.sqrt(dx * dx + dy * dy);
        const limit = 0.75 * (a.radius + b.radius);
        if (dist < limit) {
          console.warn(
            "[modules] overlap on " + klass + ": " + a.name + " <-> " + b.name +
            "  dist=" + dist.toFixed(3) + " limit=" + limit.toFixed(3)
          );
        }
      }
    }
  }
}

// Run the layout audit once at module-load. The function itself
// short-circuits when not in a Vite dev build, so prod pays only a
// single guarded branch.
auditModuleLayout();

// Clone the template into per-ship runtime state at spawn. Static
// modules are copied verbatim; engine modules are generated from the
// per-class plume count so the targetable discs sit under the visible
// thrust nozzles (same x as ENGINE_X, same y-spread as drawEnginePlumes).
export function buildModules(klass) {
  const tmpl = MODULES[klass] || [];
  const out = tmpl.map((m) => ({
    name: m.name,
    offset: { x: m.offset.x, y: m.offset.y },
    radius: m.radius,
    hp: m.hp,
    hpMax: m.hp,
    hullPenalty: m.hullPenalty,
    disabled: false,
    flash: 0,
  }));
  // Append one module per visible engine plume.
  const engineCount = ENGINES[klass] || 0;
  const engineStats = ENGINE_MODULE[klass];
  if (engineCount > 0 && engineStats) {
    // Match the plume layout in drawEnginePlumes: one line of N points
    // at x = ENGINE_X * R, evenly spaced across ±0.525 * R, slightly
    // pulled inward (×0.85) on both axes so the disc + crater paint
    // on the rear hull rather than past the silhouette.
    const ex = (ENGINE_X[klass] || -0.9) * 0.92;
    const spread = 1.05 * 0.85;
    const radius = ENGINE_RADIUS[klass] || 0.15;
    for (let i = 0; i < engineCount; i++) {
      const ey = engineCount === 1
        ? 0
        : ((i / (engineCount - 1)) - 0.5) * spread;
      out.push({
        name: "engine-" + i,
        offset: { x: ex, y: ey },
        radius,
        hp: engineStats.hp,
        hpMax: engineStats.hp,
        hullPenalty: engineStats.hullPenalty,
        disabled: false,
        flash: 0,
      });
    }
  }
  return out.length > 0 ? out : null;
}

// PD turret index → module name. PD turrets sit on a ring around the
// hull at angle (i/n)*2π; we group them by quadrant.
export function pdTurretToModuleName(klass, i, n) {
  const a = (i / n) * Math.PI * 2;
  if (klass === "battleship") return Math.cos(a) >= 0 ? "pd-bow"  : "pd-stern";
  if (klass === "carrier")    return Math.sin(a) >= 0 ? "pd-stbd" : "pd-port";
  if (klass === "cruiser")    return "pd-cluster";
  return null;
}

// Missile pod index → module name. Front half of pods → forward bay,
// rear half → aft bay (battleship). Cruisers route everything to the
// single torpedo bay.
export function podToModuleName(klass, i, n) {
  if (klass === "battleship") return i < Math.ceil(n / 2) ? "missile-fwd" : "missile-aft";
  if (klass === "cruiser")    return "torpedo-bay";
  return null;
}

// World point (wx, wy) → ship-local frame (un-rotated by ship.heading).
export function worldToLocal(ship, wx, wy) {
  const dx = wx - ship.pos.x;
  const dy = wy - ship.pos.y;
  const c = Math.cos(-ship.heading);
  const s = Math.sin(-ship.heading);
  return { x: dx * c - dy * s, y: dx * s + dy * c };
}

// Module's world-space center (offset rotated by ship.heading). Returns
// null only if the module doesn't exist on this ship — disabled modules
// still have a position so VFX spawners can keep emitting smoke / fire
// from the crater.
export function moduleWorldPos(ship, name) {
  const m = ship.moduleByName && ship.moduleByName[name];
  if (!m) return null;
  const R = ship.spec.radius;
  const lx = m.offset.x * R;
  const ly = m.offset.y * R;
  const c = Math.cos(ship.heading);
  const s = Math.sin(ship.heading);
  return {
    x: ship.pos.x + lx * c - ly * s,
    y: ship.pos.y + lx * s + ly * c,
  };
}

// Hit-zone inflation. The visible module disc draws at exact `m.radius`
// (matches the icon layer in ship.js), but the *hit* radius is 20%
// bigger so a near-miss still counts as a clip. Player explicitly
// asked for nodes to be easier to hit; this keeps the visual honest
// while making aim more forgiving. If you change this, also reconsider
// auditModuleLayout's overlap threshold (currently 0.75) — overlap
// between hit-radii is now ~1.2x the visual.
const HIT_INFLATE = 1.20;

// Closest alive module whose hit disc contains a ship-local point.
export function findHitModuleLocal(ship, lx, ly) {
  if (!ship.modules) return null;
  const R = ship.spec.radius;
  let best = null, bestD2 = Infinity;
  for (const m of ship.modules) {
    if (m.disabled) continue;
    const mx = m.offset.x * R;
    const my = m.offset.y * R;
    const mr = m.radius * R * HIT_INFLATE;
    const dx = lx - mx, dy = ly - my;
    const d2 = dx * dx + dy * dy;
    if (d2 <= mr * mr && d2 < bestD2) {
      best = m; bestD2 = d2;
    }
  }
  return best;
}

// All alive modules within `blastWorld` world-units of a ship-local hit
// point. Used to spread missile splash damage across adjacent modules.
export function findSplashModulesLocal(ship, lx, ly, blastWorld) {
  if (!ship.modules) return [];
  const R = ship.spec.radius;
  const out = [];
  for (const m of ship.modules) {
    if (m.disabled) continue;
    const mx = m.offset.x * R;
    const my = m.offset.y * R;
    const reach = m.radius * R * HIT_INFLATE + blastWorld;
    const dx = lx - mx, dy = ly - my;
    if (dx * dx + dy * dy <= reach * reach) out.push(m);
  }
  return out;
}

// Bomber AI: pick which module to home a missile at on a capital. Order
// of preference: PD first (clear the screen), then missiles, then
// broadsides, then anything else still alive. Returns module name or
// null if target has no modules / all dead.
export function pickBomberAimModule(target) {
  const m = pickAimModule(target);
  return m ? m.name : null;
}

// Generic module-priority picker used by AI cannon aim. Returns the
// module object (not just the name) so the caller can read `offset`
// for a world-space aim point. Order matches pickBomberAimModule:
// PD → broadside → missile → torpedo bay → laser → hangar. Engines
// are intentionally NOT in the list — they're rear-mounted and a hit
// usually lands on something else en route. PD comes first because
// destroying a screen turret materially changes the engagement; gun
// systems come next because silencing them shortens the fight.
const AIM_PRIORITY = ["pd-", "broadside-", "missile-", "torpedo-bay", "laser", "hangar"];
export function pickAimModule(target) {
  if (!target || !target.modules) return null;
  for (const prefix of AIM_PRIORITY) {
    for (const m of target.modules) {
      if (m.disabled) continue;
      if (m.name === prefix || m.name.startsWith(prefix)) return m;
    }
  }
  return null;
}

// World-space position of a module relative to its ship — same math
// as moduleWorldPos but takes a module object directly (no name
// lookup). Used by AI aim code that's already holding the module
// from pickAimModule.
export function moduleOffsetWorld(ship, module) {
  if (!ship || !module) return null;
  const R = ship.spec.radius;
  const lx = module.offset.x * R;
  const ly = module.offset.y * R;
  const c = Math.cos(ship.heading);
  const s = Math.sin(ship.heading);
  return {
    x: ship.pos.x + lx * c - ly * s,
    y: ship.pos.y + lx * s + ly * c,
  };
}
